set(CMAKE_CNA_SOURCE_FILE_EXTENSIONS cna)
set(CMAKE_CNA_OUTPUT_EXTENSION .cvt)
set(CMAKE_CNA_COMPILER_ENV_VAR "CNA")
set(CMAKE_CNA_COMPILER ${CSIRAC_ASSEMBLER})
configure_file(${CMAKE_CURRENT_LIST_DIR}/CMakeCNACompiler.cmake.in
    ${CMAKE_PLATFORM_INFO_DIR}/CMakeCNACompiler.cmake)
